---
resources:
- name: concourse-db-migration
  type: git
  source:
    uri: {{github-repository}}
    branch: {{github-branch}}
    private_key: {{github-private-key}}

- name: concourse-db-migration-artifacts
  type: s3
  source:
    bucket: {{bucket}}
    regexp: releases/concourse-db-migration-(.*).jar
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    endpoint: {{endpoint}}
    skip_ssl_verification: true
    disable_ssl: true

- name: version
  type: semver
  source:
    bucket: {{bucket}}
    key: concourse-db-migration/version
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    endpoint: {{endpoint}}
    skip_ssl_verification: true
    disable_ssl: true

- name: dev-deployment
  type: cf
  source:
    api: {{cf-api-url}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check:  true

jobs:
- name: build
  plan:
  - get: concourse-db-migration
    trigger: true
  - get: version
    params: {pre: SNAPSHOT}
  - task: build
    file: concourse-db-migration/ci/build.yml
  - put: concourse-db-migration-artifacts
    params:
      file: build-output/concourse-db-migration-*.jar
  - put: version
    params:
      file: version/number

- name: deploy-dev
  plan:
  - get: concourse-db-migration
    passed: [build]
  - get: concourse-db-migration-artifacts
    trigger: false
    passed: [build]
  - task: migrate database
    file: concourse-db-migration/ci/migrateDatabase.yml
    params:
      CF_API_URL: {{cf-api-url}}
      CF_USERNAME: {{cf-username}}
      CF_PASSWORD: {{cf-password}}
      CF_ORG: {{cf-org}}
      CF_SPACE: {{cf-space}}
      MYSQL_IP: {{mysql-ip}}
      DATABASE_NAME: {{database-name}}
      DATABASE_USERNAME: {{database-username}}
      DATABASE_PASSWORD: {{database-password}}
  - put: dev-deployment
    params:
      manifest: concourse-db-migration/manifest-dev.yml
      path: concourse-db-migration-artifacts/concourse-db-migration-*.jar