---
resources:
- name: {{project-name}}
  type: git
  source:
    uri: {{github-repository}}
    branch: {{github-branch}}
    private_key: {{github-private-key}}

- name: {{project-name}}-artifacts
  type: s3
  source:
    bucket: {{bucket}}
    regexp: releases/{{project-name}}-(.*).jar
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    endpoint: {{endpoint}}
    skip_ssl_verification: true
    disable_ssl: true

- name: version
  type: semver
  source:
    bucket: {{bucket}}
    key: {{project-name}}/version
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}
    endpoint: {{endpoint}}
    skip_ssl_verification: true
    disable_ssl: true

- name: dev-deployment
  type: cf
  source:
    api: {{cf-api-url}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check:  true

jobs:
- name: build
  plan:
  - get: {{project-name}}
    trigger: true
  - get: version
    params: {bump: patch,pre: SNAPSHOT}
  - task: build
    file: {{project-name}}/ci/build.yml
  - put: {{project-name}}-artifacts
    params:
      file: build-output/{{project-name}}-*.jar
  - put: version
    params:
      file: version/number

- name: deploy-dev
  plan:
  - get: {{project-name}}
    passed: [build]
  - get: {{project-name}}-artifacts
    trigger: false
    passed: [build]
  - task: migrate database
    file: {{project-name}}/ci/migrateDatabase.yml
    params:
      CF_API_URL: {{cf-api-url}}
      CF_USERNAME: {{cf-username}}
      CF_PASSWORD: {{cf-password}}
      CF_ORG: {{cf-org}}
      CF_SPACE: {{cf-space}}
      MYSQL_IP: {{mysql-ip}}
      DATABASE_NAME: {{database-name}}
      DATABASE_USERNAME: {{database-username}}
      DATABASE_PASSWORD: {{database-password}}
  - put: dev-deployment
    params:
      manifest: {{project-name}}/manifest-dev.yml
      path: {{project-name}}-artifacts/{{project-name}}-*.jar